version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: fastbreak
      POSTGRES_PASSWORD: Dev@123!
      POSTGRES_DB: torQ
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  postgres-data:


# use docker-compose up -d